### PR TITLE
Add dlang-bot to the tested projects

### PR DESCRIPTION
**Pull request by wilzbach**
It's currently broken again with `master`:

```
/home/seb/dlang/dmd/generated/linux/release/64/../../../../../phobos/std/algorithm/iteration.d-mixin-2498(2510,17): Error: cannot modify struct this._current Result with immutable members
source/dlangbot/bugzilla.d(43,9): Error: template instance std.algorithm.iteration.joiner!(MapResult!(__lambda2, Json[])) error instantiating
```

I will dig a bit into this issue, but once it's fixed, we should really add the dlang-bot to the projects tested.

### CODE REVIEW

**Comment by wilzbach** [comment]
Respective issue for tracking the regression: https://issues.dlang.org/show_bug.cgi?id=18135

**Comment by wilzbach** [comment]
Thanks to @MartinNowak the regression was fixed in https://github.com/dlang/phobos/pull/5972
Now we just need to merge it into `master`: https://github.com/dlang/phobos/pull/5973

**Comment by MartinNowak** [comment]
Still running into regex errors :/.
https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fci/detail/PR-103/3/pipeline/197#step-603-log-32

On my local machine.
```sh
core.exception.AssertError@/home/dawg/dlang/dmd-master-2017-12-30/linux/bin64/../../src/phobos/std/regex/package.d(614): wrong match: 16168320..2560
```

**Comment by wilzbach** [comment]
Thanks to using only the first regex match (https://github.com/dlang-bots/dlang-bot/pull/176) this now passes.
